spring:
  profiles.active: dev
  application.name: InventoryManagement
---
spring:
  profiles: dev
server:
  servlet:
    context-path: /dev
  port : 7777
  
---
spring:
  profiles: production

     
    