spring:
  profiles.active: dev
  application.name: InventoryManagement
  datasource:
    url: jdbc:h2:mem:InventoryManagement
    driverClassName : org.h2.Driver
    username: sa
    password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled : true
  
server:
  port : 7778

---
spring:
  profiles: dev
server:
  servlet:
    context-path: /dev
  port : 7777

logging:
  level:
    org.springframework.cache: TRACE
---   
spring:
  profiles: production

     
    